### ISSUE TITLE
Out of memory GPU

### ISSUE THREAD

**Issue by PyxAI** [EagleW/Writing-editing-Network#4]
After splitting the data, I'm trying to train on a Tesla 40c (16gb) and immediately getting out of memory, although it is clear when starting, and empty.

Stack trace:

`Traceback (most recent call last):
  File "main.py", line 179, in <module>
    train_epoches(abstracts, model, config.epochs, teacher_forcing_ratio=1)
  File "main.py", line 155, in train_epoches
    target_variables, model, teacher_forcing_ratio)
  File "main.py", line 129, in train_batch
    target_variable, teacher_forcing_ratio)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 492, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/sharedfolder/omri/Writing-editing-Network/Writing-editing network/seq2seq/fb_seq2seq.py", line 31, in forward
    teacher_forcing_ratio=teacher_forcing_ratio)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 492, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/sharedfolder/omri/Writing-editing-Network/Writing-editing network/seq2seq/DecoderRNNFB.py", line 103, in forward
    decoder_hidden, encoder_outputs, function=function)
  File "/root/sharedfolder/omri/Writing-editing-Network/Writing-editing network/seq2seq/DecoderRNNFB.py", line 75, in forward_step
    output_states, hidden = self.rnn(embedded, hidden)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 492, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 200, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 2.03 GiB (GPU 0; 15.90 GiB total capacity; 13.01 GiB already allocated; 493.88 MiB free; 1.74 GiB cached)`

**Comment by EagleW** [comment]
@PyxAI Thank you for your interest in our research! You can adjust your batch size inside main.py line 24 from 240 to 50. Also, may I ask which version of the PyTorch did you use?

**Comment by PyxAI** [comment]
@EagleW Thank you for your quick reply.
I will try that.
I am using PyTorch version 1.1
